travis:
  secure:
    BINSTAR_TOKEN: pafCHWkZpczZd7hY1JhxNfwB39cSYeDyYEjoTMFMLogt3N9pafDxb+jjT4D9gzVRM5PT4vYQVXdBBuDC7cRExxNoSolCB/VkZ6ScIDTcIXVcpR0QnMLmjcYwnjhnbW/hceNjM9rqG76zMoqzxdOthZar/ZTiqrfbSjYggGp51AhzN/vCHEkUoAhETT5DDgsnWmypuXAeqL3QBO4dVIayYtbtO2YUOvfuRG3XndaIzUO9JW97aczdZB955cJhjWXZ2rfi7tWl56CSfAvQhs0tKKO91ZDdPdUz2eT4T6ScRBR1wc7ep9CAFkwmadPuV0wGDeqhe9AB9DZm/xModxD6KHrxqJ0NeciaKe1qaYWthj4MoEWbAWLgf+/bSWZ+OqCT5cqpkalX/OCuJjyFn9joOqG+pLtblSd2mYOqt734JhroWMT5JXrn5K7m5jaxHwTddbdTMW5i7Cran8NXuiBd9fXwe3uH6JAktfeY+jX21Q21plg+vnMXYHklEcxGM0YG4HKAYLILNp/QGyP+cUlDtu7Eyf9CLZ/Auu+Sk636t+ErPGFBXuwW1vmEYCbQlCQMUaNJSXtvRg5oVF137fX6L6t5QvR2zt/muWM4GQfzdZtoVcoQM3M/k1Bss4XP5I8SeZBiM4c7uK+wlgnXl5UCFliD/l3w/EkG4PwIQizpzuk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
