travis:
  secure:
    BINSTAR_TOKEN: N7hsxArC+1G9iGPaju4rZpjsbVp2RfwnCltQvNacoi69mWGMfSEw/VJA4hB1i/EXeYgaaYOdlLuqlfDwpopr2wsG68O4sLmG+JlGYHfnT9awmoaEwURGa+GMvIlupw2QG8pQbg2UgqVsvzkTCncqLjW3loKwK/ZgLz9nHiOKkKJ9GaR/J2Q1yitqghtSDqFtMqZ9tIAIhxXrjjlDpvvaUVCOKnpz478KxWfDxCfAcIedaQom3LKwzVgtM0jsZCGbO3+PiIqLGa7XcZ1gvo1LnbuUpqAOZ+sCawl94+XKvWoYWtxwvUfRMTUuQMEFXW2VKyuUXI9aytA2AZLYHIaJgmAOVpV62uFkgz/L0PFL7SKVhp8xLc4rXljMKHO8dgQIZzGGh5L8DDhyg8paSWEP4tmBYQ/uj6S94e+ZvFgh8LAR265uZpckx/6/k7zDwqUiOlLpfKOCABqrD3QS5yoFZ6AixKJ3FWPtF0TgYl96hISBZx5JLe2xsS6TEIv+4pjZaEo22F6UHJ5ngxkS2hs9GW5MTOVdMSjvqMOktSBSWN7OIUaNaBkglIZdkjUdA85hYEiz/qNczD7ztX7PV/aoLLUCJHTACxGPhavLfKVGHlN70kTa8Nu31DSyQeU6vQhunAcJNOhxosso87xn3TSxkth+xUebyxxx+5E9ezZeKMc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
